//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.23 at 09:11:30 PM ART 
//


package com.das.soapconsumer.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serviceAvailability" type="{http://das.com/soap}serviceAvailability"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceAvailability"
})
@XmlRootElement(name = "getAvailabilityResponse")
public class GetAvailabilityResponse {

    @XmlElement(required = true)
    protected ServiceAvailability serviceAvailability;

    /**
     * Gets the value of the serviceAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceAvailability }
     *     
     */
    public ServiceAvailability getServiceAvailability() {
        return serviceAvailability;
    }

    /**
     * Sets the value of the serviceAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceAvailability }
     *     
     */
    public void setServiceAvailability(ServiceAvailability value) {
        this.serviceAvailability = value;
    }

}
