//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.23 at 09:11:30 PM ART 
//


package com.das.soapconsumer.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for statDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="batchStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="batchEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="openAssistanceCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="finishedAssistanceCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="canceledAssistanceCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="messageCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statDto", propOrder = {
    "userId",
    "batchStart",
    "batchEnd",
    "openAssistanceCount",
    "finishedAssistanceCount",
    "canceledAssistanceCount",
    "messageCount"
})
public class StatDto {

    protected Long userId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar batchStart;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar batchEnd;
    protected Long openAssistanceCount;
    protected Long finishedAssistanceCount;
    protected Long canceledAssistanceCount;
    protected Long messageCount;

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserId(Long value) {
        this.userId = value;
    }

    /**
     * Gets the value of the batchStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBatchStart() {
        return batchStart;
    }

    /**
     * Sets the value of the batchStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBatchStart(XMLGregorianCalendar value) {
        this.batchStart = value;
    }

    /**
     * Gets the value of the batchEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBatchEnd() {
        return batchEnd;
    }

    /**
     * Sets the value of the batchEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBatchEnd(XMLGregorianCalendar value) {
        this.batchEnd = value;
    }

    /**
     * Gets the value of the openAssistanceCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOpenAssistanceCount() {
        return openAssistanceCount;
    }

    /**
     * Sets the value of the openAssistanceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOpenAssistanceCount(Long value) {
        this.openAssistanceCount = value;
    }

    /**
     * Gets the value of the finishedAssistanceCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFinishedAssistanceCount() {
        return finishedAssistanceCount;
    }

    /**
     * Sets the value of the finishedAssistanceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFinishedAssistanceCount(Long value) {
        this.finishedAssistanceCount = value;
    }

    /**
     * Gets the value of the canceledAssistanceCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCanceledAssistanceCount() {
        return canceledAssistanceCount;
    }

    /**
     * Sets the value of the canceledAssistanceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCanceledAssistanceCount(Long value) {
        this.canceledAssistanceCount = value;
    }

    /**
     * Gets the value of the messageCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMessageCount() {
        return messageCount;
    }

    /**
     * Sets the value of the messageCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMessageCount(Long value) {
        this.messageCount = value;
    }

}
